<?php

$data_configure=array(
    "types"=>array(0=>'落地页下载地址配置'),
    'templates'=>array(
        0=>array(
            'fields'=>array(
                0=>array('name'=>'id','label'=>'ID','type'=>'auto','show'=>true),
                1=>array('name'=>'label','label'=>'渠道名称','type'=>'text','show'=>true),
                2=>array('name'=>'str1','label'=>'渠道号','type'=>'text','show'=>true),
                3=>array('name'=>'str2','label'=>'下载地址','type'=>'text','show'=>true),
            )
        )
    ),
    'permits'=>array(
        0=>array('add'=>true,'delete'=>true,'edit'=>true)
    )
);
?>