<div class="footer">
    <span class="logo" style = "height:130px"><img src="<?php BASE_URL() ?>v2/images/logo.png"></span>
    <div class="cr">
        <p class="link"> <a target="_blank" href="//www.idreamsky.com/homes/about">关于我们</a> | <a target="_blank" href="//www.idreamsky.com/jobs">诚聘英才</a> | <a target="_blank" href="//www.idreamsky.com/homes/contact">联系我们</a> | <a target="_blank" href="//www.idreamsky.com/homes/events">公司大事记</a> | <a target="_blank" href="//www.idreamsky.com/homes/customer_service">客服中心</a> | <a target="_blank" href="//www.idreamsky.com/homes/contact">网站合作</a> | <a target="_blank" href="//www.idreamsky.com/homes/disclaimer">用户协议</a> | <a target="_blank" href="//www.idreamsky.com/homes/disclaimer">家长控制</a> </p>
        <p> <span>本游戏适合6岁以上的玩家进入</span>  <span> <br/> Copyright©2009-2014  深圳市创梦天地科技有限公司  版权所有</span> <a target="_blank" href="//www.sznet110.gov.cn/netalarm/index.jsp"> <img src="<?php BASE_URL() ?>v2/images/shenwang.jpg" width="16" alt="深圳网络警察报警平台"> </a> <a target="_blank" href="//www.sznet110.gov.cn/webrecord/doquery.jsp"> <img src="<?php BASE_URL() ?>v2/images/anwang.jpg" alt="公共信息安全网络监察" width="16"> </a> <a target="_blank" href="//net.china.com.cn/index.htm"> <img src="<?php BASE_URL() ?>v2/images/jubao.jpg" alt="经营性网站备案信息" width="16"> </a> <a target="_blank" href="//www.miitbeian.gov.cn/publish/query/indexFirst.action"> <img src="<?php BASE_URL() ?>v2/images/beian.jpg" alt="不良信息举报中心" width="16"> </a> <a target="_blank" href="http://sq.ccm.gov.cn/ccnt/sczr/service/business/emark/toDetail/483588C2B60B4E39A3D15E72F802863E"> <img src="<?php BASE_URL() ?>v2/images/wenhuajingying.png" alt="网络文化经营许可证" width="16"> </a> <a target="_blank" href="http://sq.ccm.gov.cn:80/ccnt/sczr/service/business/emark/gameNetTag/4028c08b4dd1e476014dd29b68cc059c"> <img src="<?php BASE_URL() ?>v2/images/w_foot2_icon2.png" alt="电子标签" width="16"> </a></p>
        <p>粤网文〔2016〕6871-1632号 新广出审[2016]5号 </p>
        <p>出版物号：ISBN 978-7-900267-58-0 文网游进字〔2015〕0059号</p>
    </div>
    <div class="zg"><strong>健康游戏忠告：</strong>抵制不良游戏，拒绝盗版游戏。注意自我保护，谨防上当受骗。适度游戏益脑，沉迷游戏伤身。合理安排时间，享受健康生活。</div>
</div>
    <script src="//dl.gamdream.com/website/timeStyleChange.js"></script>
<a style="display:none" href="http://webscan.360.cn/index/checkwebsite/url/mv.uu.cc"><img border="0" src="http://webscan.360.cn/status/pai/hash/067c525eba9309a9aadb56900095d6e5"/></a>